name: project_drone
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  geolocator: ^12.0.0
  flutter_map: ^5.0.0
  get: ^4.6.5
  url_launcher: ^6.0.12
  provider: ^6.0.5
  liquid_progress_indicator: ^0.4.0
  liquid_progress_indicator_v2: ^0.5.0
  flutter_screenutil: ^5.0.0
  screenshot: ^3.0.0
  image: ^3.0.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  flutter_typeahead: ^5.2.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.3.0
  http: ^1.2.2
  firebase_storage: ^12.2.0
  firebase_auth: ^5.2.0
  firebase_database: ^11.1.0
  flutter_open_street_map: ^0.0.4
  sleek_circular_slider: ^2.0.1
  toggle_switch: ^2.1.0
  syncfusion_flutter_gauges: ^24.1.45
  flutter_joystick: ^0.0.4
  location: ^6.0.2
  xml: ^6.1.0
  flutter_asset_manager: ^0.0.2
  google_fonts: any
  flutter_svg: ^2.0.10+1
  percent_indicator: ^4.2.2
  animated_widgets: ^1.1.0
  file_picker: ^8.1.2
  path: ^1.9.0
  flutter_marquee: ^2.0.1
  flutter_polyline_points: ^2.1.0
  dio: 4.0.0
  flutter_google_maps_webservices: ^1.1.1
  googlemaps_flutter_webservices: ^1.0.2
  flutter_inappwebview: ^6.1.5
  flutter_keyboard_visibility: ^6.0.0
  fl_chart: ^0.70.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/logo.png
    - images/ugv_active.png
    - images/ugv_dead.png

