// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMAx8lJLo9t_4M-ufstXDu8teLIvYDPXs',
    appId: '1:755512017161:web:9ddb85d042683e8dbbd3d8',
    messagingSenderId: '755512017161',
    projectId: 'iotcar-9259e',
    authDomain: 'iotcar-9259e.firebaseapp.com',
    databaseURL: 'https://iotcar-9259e-default-rtdb.firebaseio.com',
    storageBucket: 'iotcar-9259e.appspot.com',
    measurementId: 'G-QBXDQ5WCKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4KeIU0zp8VWxv87UZnwXXQ7Mi7B4J4ZI',
    appId: '1:755512017161:android:c69215a3c627e170bbd3d8',
    messagingSenderId: '755512017161',
    projectId: 'iotcar-9259e',
    databaseURL: 'https://iotcar-9259e-default-rtdb.firebaseio.com',
    storageBucket: 'iotcar-9259e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGcjtoY2hclFtLwT6F-MtGvMW22cnxikA',
    appId: '1:755512017161:ios:d9ca7eef741f29e3bbd3d8',
    messagingSenderId: '755512017161',
    projectId: 'iotcar-9259e',
    databaseURL: 'https://iotcar-9259e-default-rtdb.firebaseio.com',
    storageBucket: 'iotcar-9259e.appspot.com',
    iosBundleId: 'com.example.projectDrone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGcjtoY2hclFtLwT6F-MtGvMW22cnxikA',
    appId: '1:755512017161:ios:d9ca7eef741f29e3bbd3d8',
    messagingSenderId: '755512017161',
    projectId: 'iotcar-9259e',
    databaseURL: 'https://iotcar-9259e-default-rtdb.firebaseio.com',
    storageBucket: 'iotcar-9259e.appspot.com',
    iosBundleId: 'com.example.projectDrone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMAx8lJLo9t_4M-ufstXDu8teLIvYDPXs',
    appId: '1:755512017161:web:a794e523fbe5f65bbbd3d8',
    messagingSenderId: '755512017161',
    projectId: 'iotcar-9259e',
    authDomain: 'iotcar-9259e.firebaseapp.com',
    databaseURL: 'https://iotcar-9259e-default-rtdb.firebaseio.com',
    storageBucket: 'iotcar-9259e.appspot.com',
    measurementId: 'G-3QQECNWV1T',
  );
}
